sudo: required
services: 
  - docker 

before_install:
  - docker build -t hmuruges/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hmuruges/docker-react npm run test -- --coverage
