sudo: required
services: 
  - docker 

before_install:
  - docker build -t hmuruges/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hmuruges/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeantalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-570758562303"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY